#-*- coding: utf-8-unix -*-
quarkus.ironjacamar.casual-one.ra.kind=casual
quarkus.ironjacamar.casual-one.ra.config.host=10.109.83.94
quarkus.ironjacamar.casual-one.ra.config.port=7771
quarkus.ironjacamar.casual-one.ra.config.network-connection-pool-size=1
quarkus.ironjacamar.casual-one.ra.config.network-connection-pool-name=casual-one-pool
quarkus.ironjacamar.casual-one.ra.config.inbound-server-port=7772
quarkus.naming.enable-jndi=true
quarkus.package.jar.type=uber-jar
